spring.application.name=contact-management-system

# In-memory H2 database
spring.datasource.url=jdbc:h2:mem:contact
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Swagger / OpenAPI docs
springdoc.api-docs.title=Contact API
springdoc.api-docs.version=OPENAPI_3_0
springdoc.api-docs.description=API for managing contacts

# Allow requests from your Vercel frontend (CORS config)
spring.web.cors.allowed-origins=https://contact-management-system-git-main-mak0786s-projects.vercel.app
