spring.application.name=contact-management-system

spring.datasource.url=jdbc:h2:mem:contact;
spring.datasource.driverClassName= org.h2.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

springdoc.api-docs.title=Contact API
springdoc.api-docs.version=OPENAPI_3_0
springdoc.api-docs.description=API for managing contacts
